apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-orchestrator-config
  namespace: ai-orchestrator
data:
  redis_url: "redis://redis-service:6379"
  neo4j_uri: "bolt://neo4j-service:7687"
  qdrant_url: "http://qdrant-service:6333"
  log_level: "INFO"
