# docker-compose.yml
# Supporting services for the MCP server

version: '3.8'

services:
  neo4j:
    image: neo4j:5.13
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD:-password}
      NEO4J_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - mcp_network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - mcp_network

  mcp_server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITTODOC_API_KEY=${GITTODOC_API_KEY}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./repositories:/app/repositories
      - ./config:/app/config
      - ./logs:/app/logs
    depends_on:
      - neo4j
      - qdrant
    networks:
      - mcp_network

volumes:
  neo4j_data:
  neo4j_logs:
  qdrant_data:

networks:
  mcp_network:
    driver: bridge
